
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jdbc_test
    username: postgres
    password: NewPassword@121097
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    drop-first: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.github.youssefagagg: DEBUG
    org.springframework.jdbc.core: TRACE