--liquibase formatted sql
--changeset youssef:V1.0.0-1
-- create
CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id)

);
--changeset youssef:V1.0.0-2
CREATE TABLE user_authority
(
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT
);
ALTER TABLE user_authority
    ADD CONSTRAINT FK_USER_AUTHORITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

--changeset youssef:V1.0.0-3
CREATE TABLE user_otp
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp    VARCHAR(255) NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_user_otp PRIMARY KEY (id)

);
ALTER TABLE user_otp
    ADD CONSTRAINT FK_USER_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
--changeset youssef:V1.0.0-4

ALTER TABLE users
    ADD column file_extensions VARCHAR(255)[];
